### PR TITLE
FIX: Broken page in the navigation

### PR DESCRIPTION
**Pull request by Antonyjin**
Usage.md and Documentation.md were the same page, so we keeped usage.md but it was not deleted from the navigation insided the mkdocs file.

Solution: Removing the navigation related to Documentation.md

### CODE REVIEW

**Comment by Antonyjin** [comment]
I squashed some commits to make it clear, there were to much failing tests that were useless.

**Review by hoh — COMMENTED** [review]
Why not use the [strict mode](https://www.mkdocs.org/user-guide/cli/#mkdocs-build) of `mkdocs build` ?

> -s, --strict / --no-strict 	boolean 	Enable strict mode. This will cause MkDocs to abort the build on any warnings. 	None

**Comment by Antonyjin** [comment]
I had no idea this flag existed. I'm going to try them out right now

**Review by hoh — APPROVED** [review]

**Comment by hoh** [comment]
Thanks ! Can you also fix the warning ?



```
WARNING -  Doc file 'tools/webconsole/write_your_code.md' contains a relative link '../languages/python/index.html', but the target 'tools/languages/python/index.html' is not found among documentation files.
```

https://github.com/aleph-im/aleph-docs/actions/runs/8691915274/job/23835282294?pr=88

**Comment by Antonyjin** [comment]
Yes I'm on it, it is a bit strange because this warning did not appear when I tried locally but it appears on github

**Comment by hoh** [comment]
The commit history of this branch could not be rebased due to a merge commit. 
I rewrote history as 2 commits.

**Pull request merged**
