### PR TITLE
63 changing the automated navigation to a manual navigation

### PR DESCRIPTION
**Pull request by Antonyjin**

### CODE REVIEW

**Comment by Antonyjin** [comment]
Can you tell me if you like the way I've organized the different sections?

**Comment by hoh** [comment]
The main navigation should follow the following order:

Overview
Protocol
Nodes
Tools
Libraries
Computing
Guides

Guides could be renamed Tutorials :thinking:

**Comment by Antonyjin** [comment]
Okay! Do you want me to wait for the confirmation of Mike before pushing the changes?

**Review by MHHukiewitz — APPROVED** [review]
LGTM

**Pull request merged**
