### PR TITLE
Fix: Directory name and tabs formatted inadequately.

### PR DESCRIPTION
**Pull request by Antonyjin**
The name of te directory was not capitalize.
The tabs did not show in the documentation

Solution: Capitalize the name of the directory.
Add the missing plugin in the .yml file.

### CODE REVIEW

**Comment by Antonyjin** [comment]
> The name of the directory should still be lowercase `python-sdk`.

I can't find a solution other than using the "nav" parameter in the yml file.
This means defining a custom navigation for the documentation, as it's basically automated.

Would this be relevant in your point of view or do you know of another way?

**Comment by hoh** [comment]
I am not the biggest fan of the manual navigation, but I think it will also allow us to reorder the different sections of the navigation, which would be highly useful (Guides before Computing, ...)

**Comment by Antonyjin** [comment]
> I am not the biggest fan of the manual navigation, but I think it will also allow us to reorder the different sections of the navigation, which would be highly useful (Guides before Computing, ...)

I feel the same way about it. I also prefer automated navigation, which won't require any management to add new routes every time we want to add something (the same goes for modifications).

But I agree that it could be useful in some cases

I think both are good, so if we decide to do manual navigation, I might do it.

**Comment by hoh** [comment]
@Antonyjin should we close this PR ?

**Comment by Antonyjin** [comment]
Yes, I think it's no longer relevant because of other PRs that also corrected these problems.

**Pull request closed without merging**
